const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.scrollto,
		C3.Behaviors.custom,
		C3.Behaviors.Timer,
		C3.Behaviors.wrap,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Tween,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.gamepad,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Behaviors.custom.Acts.AccelerateAngle,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.custom.Cnds.CompareSpeed,
		C3.Behaviors.custom.Acts.SetSpeed,
		C3.Behaviors.custom.Exps.Speed,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetLayoutScale
	];
};
self.C3_JsPropNameTable = [
	{Sine: 0},
	{Space: 0},
	{TopPlanet: 0},
	{BottomPlanets: 0},
	{LastPositionX: 0},
	{LastPositionY: 0},
	{ScrollTo: 0},
	{Custom: 0},
	{Timer: 0},
	{Wrap: 0},
	{Spaceship: 0},
	{Keyboard: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Laser: 0},
	{LaserMuzzleFlash: 0},
	{EngineFire: 0},
	{Tween: 0},
	{EngineDistortionMask: 0},
	{Heath: 0},
	{Asteroid32: 0},
	{Explosion: 0},
	{Asteroid16: 0},
	{Asteroid8: 0},
	{Rotate: 0},
	{AsteroidParticle: 0},
	{EngineTrail: 0},
	{GameManager: 0},
	{LaserTrailParticles: 0},
	{LaserHitParticles: 0},
	{Fade: 0},
	{TextFont: 0},
	{Gamepad: 0},
	{Asteroids: 0},
	{ACCELERATION: 0},
	{MAXSPEED: 0},
	{TARGETFRAMERATE: 0},
	{Direction: 0},
	{Amount: 0},
	{PositionX: 0},
	{PositionY: 0},
	{Strength: 0},
	{Duration: 0}
];

self.InstanceType = {
	Space: class extends self.ISpriteInstance {},
	TopPlanet: class extends self.ISpriteInstance {},
	BottomPlanets: class extends self.ISpriteInstance {},
	Spaceship: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Laser: class extends self.ISpriteInstance {},
	LaserMuzzleFlash: class extends self.ISpriteInstance {},
	EngineFire: class extends self.ISpriteInstance {},
	EngineDistortionMask: class extends self.ISpriteInstance {},
	Asteroid32: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Asteroid16: class extends self.ISpriteInstance {},
	Asteroid8: class extends self.ISpriteInstance {},
	AsteroidParticle: class extends self.ISpriteInstance {},
	EngineTrail: class extends self.ISpriteInstance {},
	GameManager: class extends self.ISpriteInstance {},
	LaserTrailParticles: class extends self.ISpriteInstance {},
	LaserHitParticles: class extends self.IParticlesInstance {},
	TextFont: class extends self.ISpriteFontInstance {},
	Gamepad: class extends self.IInstance {},
	Asteroids: class extends self.ISpriteInstance {}
}